## 4.8 Grouping Data & Aggregating Variables

In [5]:
# Import libraries

import pandas as pd
import numpy as np
import os

In [4]:
# reuseable data path
file_location = r'C:\Users\natta\Downloads\Achievement 4 project'

In [6]:
# importing data frame

ords_prods_merge = pd.read_pickle(os.path.join(file_location, '02 Data', 'prepared data' , 'orders_products_merged_v2.pkl'))

In [7]:
# creating subset

df = ords_prods_merge[:1000000]

In [6]:
# cheaking data

df.shape

(1000000, 20)

In [45]:
df.head(50)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,Unnamed: 0_y,product_name,aisle_id,department_id,prices,_merge,price_range_loc,busiest_day,Busiest_day,Busiest_period_of_day
0,0,2539329,1,1,2,8,NaN,196,1,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average_orders
1,1,2398795,1,2,3,7,15.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Most_orders
2,2,473747,1,3,3,12,21.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Most_orders
3,3,2254736,1,4,4,7,29.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest_days,Most_orders
4,4,431534,1,5,4,15,28.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest_days,Most_orders
5,5,3367565,1,6,2,7,19.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
6,6,550135,1,7,1,9,20.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
7,7,3108588,1,8,1,14,14.0,196,2,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
8,8,2295261,1,9,1,16,0.0,196,4,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
9,9,2550362,1,10,4,8,30.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest_days,Average_orders
10,144,2968173,15,15,1,9,7.0,196,2,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
11,146,1870022,15,17,2,16,8.0,196,6,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
12,147,1911383,15,18,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
13,150,2715276,15,21,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
14,151,487368,15,22,1,10,14.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Average_orders
15,209,2293453,19,2,5,14,6.0,196,3,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
16,212,1973799,19,5,6,12,8.0,196,15,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
17,214,532817,19,7,4,17,6.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest_days,Most_orders
18,232,1573906,21,10,3,10,6.0,196,2,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Average_orders
19,458,1593000,31,10,3,8,7.0,196,17,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Average_orders
20,465,2231262,31,17,3,11,8.0,196,14,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Most_orders
21,617,2580647,43,6,4,16,4.0,196,9,0,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest_days,Most_orders
22,620,2187180,43,9,4,12,3.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Least busy,Slowest_days,Most_orders
23,751,2497897,52,1,1,9,NaN,196,4,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
24,752,1318871,52,2,1,10,7.0,196,5,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Average_orders
25,753,1261384,52,3,1,10,7.0,196,3,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Average_orders
26,755,580568,52,5,2,10,8.0,196,6,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average_orders
27,757,2428073,52,7,2,7,8.0,196,5,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
28,759,342306,52,9,1,11,7.0,196,5,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
29,760,1520353,52,10,2,10,8.0,196,4,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average_orders
30,761,2542086,52,11,2,9,7.0,196,3,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
31,762,944694,52,12,1,16,6.0,196,7,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
32,765,1268191,52,15,2,11,8.0,196,3,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
33,767,1122089,52,17,2,10,6.0,196,4,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average_orders
34,768,1498922,52,18,2,10,14.0,196,6,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average_orders
35,769,180919,52,19,3,8,8.0,196,4,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Average_orders
36,771,2695875,52,21,5,10,30.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Average_orders
37,1022,3205960,67,1,3,11,NaN,196,1,0,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Most_orders
38,1023,970922,67,2,1,15,5.0,196,2,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
39,1024,596585,67,3,1,13,7.0,196,2,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
40,1025,2037087,67,4,2,9,8.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
41,1026,2474111,67,5,3,14,8.0,196,2,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Most_orders
42,1027,1568481,67,6,3,12,7.0,196,2,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Slowest_days,Most_orders
43,1029,2048527,67,8,2,11,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
44,1030,2389031,67,9,2,14,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
45,1031,2378562,67,10,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Average_orders
46,1032,1515698,67,11,1,11,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders
47,1033,1928050,67,12,2,12,8.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Regularly busy,Most_orders
48,1034,1949274,67,13,1,10,6.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Average_orders
49,1035,551869,67,14,1,9,7.0,196,1,1,195,Soda,77,7,9.0,both,Mid-range product,Regularly busy,Busiest_days,Most_orders

In [9]:
df.groupby('product_name')

In [46]:
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
4                18.825780
7                17.472355
13               17.993423
14               19.246334
16               19.463012
17               11.294069
19               19.305237
20               17.599636

In [47]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
4                18.825780   1  99
7                17.472355   1  99
13               17.993423   1  99
14               19.246334   1  99
16               19.463012   1  99
17               11.294069   1  98
19               19.305237   1  99
20               17.599636   1  99

Task

In [ ]:
# Task 2  aggregated mean of the “order_number” column grouped by “department_id” for entire dataframe.

In [49]:
ords_prods_merge.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

# Task 3 dataset looks almost same.The means of the two sets are extremely similar, with the first 1000000 having a little higher mean than the total dataframe.

In [ ]:
# task 4 creating a loyalty flag for existing customers using the transform() and loc() functions.

In [50]:
#Transforming 

ords_prods_merge['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

In [51]:
# data set cheaking
ords_prods_merge.head(50)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,Busiest_day,Busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag,order_frequency,order_frequency_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
16,212,1973799,19,5,6,12,8.0,196,15,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
17,214,532817,19,7,4,17,6.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
18,232,1573906,21,10,3,10,6.0,196,2,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,33.0,Regular customer,6.100000,Low spender,30.0,Non-frequent customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
23,751,2497897,52,1,1,9,NaN,196,4,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
37,1022,3205960,67,1,3,11,NaN,196,1,0,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer

In [ ]:

#Creating and assigning the loyalty flag in the new column

In [54]:
ords_prods_merge.loc[ords_prods_merge['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'

In [56]:
ords_prods_merge.loc[(ords_prods_merge['max_order'] <= 40) & (ords_prods_merge['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'

In [58]:
ords_prods_merge.loc[ords_prods_merge['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [59]:
# Checking frequency of flag

ords_prods_merge['loyalty_flag'].value_counts(dropna = False)

NaN                 31404859
Regular customer      463844
Loyal customer        335086
New customer          201070
Name: loyalty_flag, dtype: int64

In [60]:
#Checking data frame
ords_prods_merge.head(50)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,Busiest_day,Busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag,order_frequency,order_frequency_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
16,212,1973799,19,5,6,12,8.0,196,15,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
17,214,532817,19,7,4,17,6.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
18,232,1573906,21,10,3,10,6.0,196,2,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,33.0,Regular customer,6.100000,Low spender,30.0,Non-frequent customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
23,751,2497897,52,1,1,9,NaN,196,4,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
37,1022,3205960,67,1,3,11,NaN,196,1,0,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer

In [ ]:
# Task 5  loyalty flag you created and check the basic statistics of the product prices for each loyalty category (Loyal Customer, Regular Customer, and New Customer)

In [62]:
ords_prods_merge.groupby('loyalty_flag').agg({'prices' : ['mean', 'min', 'max']})

                    prices
                      mean  min   max
loyalty_flag
Loyal customer    7.897711  1.0  14.8
New customer      7.738627  1.0  14.8
Regular customer  7.798050  1.0  14.8

In [ ]:
# task 6 put flag as low spender and high spender for  marketing

In [63]:
# Generating summary stats (used .head due to high number of customers)

ords_prods_merge.groupby('user_id').agg({'prices' : ['mean', 'min', 'max']}).head(20)

             prices
               mean  min      max
user_id
1          6.367797  1.0     14.0
2          7.515897  1.3     14.8
3          8.197727  1.3     14.4
4          8.205556  1.4     14.6
5          9.189189  3.2     14.8
6          8.471429  1.8     19.6
7          7.466990  1.1     23.2
8          8.781633  1.1     14.4
9          7.607895  1.2     19.3
10         8.651049  1.0     24.2
11         8.328723  1.4     14.7
12         8.116216  1.1     14.6
13         8.708642  1.0     13.6
14         8.014286  1.1     23.0
15         3.980556  1.9      9.0
16         8.228571  1.1     18.2
17       108.648299  1.1  14900.0
18         7.702564  2.6     18.5
19         8.372059  1.0     23.9
20         5.409091  2.2      8.8

In [64]:
# Transforming
ords_prods_merge['spending'] = df.groupby(['user_id'])['prices'].transform(np.mean)

In [65]:
#Checking data frame
ords_prods_merge.head(50)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,Busiest_day,Busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag,order_frequency,order_frequency_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
16,212,1973799,19,5,6,12,8.0,196,15,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
17,214,532817,19,7,4,17,6.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
18,232,1573906,21,10,3,10,6.0,196,2,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,33.0,Regular customer,6.100000,Low spender,30.0,Non-frequent customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
23,751,2497897,52,1,1,9,NaN,196,4,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
37,1022,3205960,67,1,3,11,NaN,196,1,0,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer

In [66]:
# Creating flags as 'low spender' and 'high spender'

ords_prods_merge.loc[ords_prods_merge['spending'] < 10, 'spending_flag'] = 'Low spender'

In [67]:
ords_prods_merge.loc[ords_prods_merge['spending'] > 10, 'spending_flag'] = 'High spender'

In [68]:
# cheaking data frame
ords_prods_merge.head(50)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,Busiest_day,Busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag,order_frequency,order_frequency_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
16,212,1973799,19,5,6,12,8.0,196,15,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
17,214,532817,19,7,4,17,6.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
18,232,1573906,21,10,3,10,6.0,196,2,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,33.0,Regular customer,6.100000,Low spender,30.0,Non-frequent customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
23,751,2497897,52,1,1,9,NaN,196,4,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
37,1022,3205960,67,1,3,11,NaN,196,1,0,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer

In [ ]:
# task 7 Create an order frequency flag that marks the regularity of a user’s ordering behavior according to the median in the “days_since_prior_order” column

In [69]:

ords_prods_merge.groupby('user_id').agg({'days_since_prior_order' : ['mean']})

        days_since_prior_order
                          mean
user_id
1                    20.259259
2                    15.967033
3                    11.487179
4                    15.357143
5                    14.500000
...                        ...
206205               20.666667
206206                4.042705
206207               14.879397
206208                7.442105
206209               20.275862

[206209 rows x 1 columns]

In [70]:
#transformation 
ords_prods_merge['order_frequency'] = ords_prods_merge.groupby(['user_id'])['days_since_prior_order'].transform(np.max)

In [71]:
# cheaking data frame
ords_prods_merge.head(50)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,Busiest_day,Busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag,order_frequency,order_frequency_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
16,212,1973799,19,5,6,12,8.0,196,15,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
17,214,532817,19,7,4,17,6.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
18,232,1573906,21,10,3,10,6.0,196,2,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,33.0,Regular customer,6.100000,Low spender,30.0,Non-frequent customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
23,751,2497897,52,1,1,9,NaN,196,4,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
37,1022,3205960,67,1,3,11,NaN,196,1,0,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer

In [73]:
# Creating Flag  as 'Non-frequent customer',
ords_prods_merge.loc[ords_prods_merge['order_frequency'] > 20, 'order_frequency_flag'] = 'Non-frequent customer'

In [74]:
ords_prods_merge.loc[ords_prods_merge['order_frequency'] < 20, 'order_frequency_flag'] = 'Regular customer'

In [76]:
ords_prods_merge.loc[ords_prods_merge['order_frequency'] <= 10, 'order_frequency_flag'] = 'Frequent customer'

In [77]:
ords_prods_merge.head(50)

,Unnamed: 0_x,order_id,user_id,order_number,orders_day_of_week,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,price_range_loc,busiest_day,Busiest_day,Busiest_period_of_day,max_order,loyalty_flag,spending,spending_flag,order_frequency,order_frequency_flag
0,0,2539329,1,1,2,8,NaN,196,1,0,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
1,1,2398795,1,2,3,7,15.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
2,2,473747,1,3,3,12,21.0,196,1,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
3,3,2254736,1,4,4,7,29.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
4,4,431534,1,5,4,15,28.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
5,5,3367565,1,6,2,7,19.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
6,6,550135,1,7,1,9,20.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
7,7,3108588,1,8,1,14,14.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
8,8,2295261,1,9,1,16,0.0,196,4,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
9,9,2550362,1,10,4,8,30.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Average_orders,10.0,New customer,6.367797,Low spender,30.0,Non-frequent customer
10,144,2968173,15,15,1,9,7.0,196,2,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
11,146,1870022,15,17,2,16,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
12,147,1911383,15,18,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
13,150,2715276,15,21,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
14,151,487368,15,22,1,10,14.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,22.0,Regular customer,5.933333,Low spender,21.0,Non-frequent customer
15,209,2293453,19,2,5,14,6.0,196,3,0,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
16,212,1973799,19,5,6,12,8.0,196,15,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
17,214,532817,19,7,4,17,6.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,7.0,New customer,9.000000,Low spender,20.0,NaN
18,232,1573906,21,10,3,10,6.0,196,2,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,33.0,Regular customer,6.100000,Low spender,30.0,Non-frequent customer
19,458,1593000,31,10,3,8,7.0,196,17,0,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
20,465,2231262,31,17,3,11,8.0,196,14,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,17.0,Regular customer,9.000000,Low spender,10.0,Frequent customer
21,617,2580647,43,6,4,16,4.0,196,9,0,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
22,620,2187180,43,9,4,12,3.0,196,1,1,...,Mid-range product,Least busy,Slowest_days,Most_orders,9.0,New customer,9.000000,Low spender,24.0,Non-frequent customer
23,751,2497897,52,1,1,9,NaN,196,4,0,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
24,752,1318871,52,2,1,10,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
25,753,1261384,52,3,1,10,7.0,196,3,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
26,755,580568,52,5,2,10,8.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
27,757,2428073,52,7,2,7,8.0,196,5,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
28,759,342306,52,9,1,11,7.0,196,5,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
29,760,1520353,52,10,2,10,8.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
30,761,2542086,52,11,2,9,7.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
31,762,944694,52,12,1,16,6.0,196,7,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
32,765,1268191,52,15,2,11,8.0,196,3,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
33,767,1122089,52,17,2,10,6.0,196,4,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
34,768,1498922,52,18,2,10,14.0,196,6,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
35,769,180919,52,19,3,8,8.0,196,4,1,...,Mid-range product,Regularly busy,Slowest_days,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
36,771,2695875,52,21,5,10,30.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Average_orders,27.0,Regular customer,8.937209,Low spender,30.0,Non-frequent customer
37,1022,3205960,67,1,3,11,NaN,196,1,0,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
38,1023,970922,67,2,1,15,5.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
39,1024,596585,67,3,1,13,7.0,196,2,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
40,1025,2037087,67,4,2,9,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
41,1026,2474111,67,5,3,14,8.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
42,1027,1568481,67,6,3,12,7.0,196,2,1,...,Mid-range product,Regularly busy,Slowest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
43,1029,2048527,67,8,2,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
44,1030,2389031,67,9,2,14,7.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
45,1031,2378562,67,10,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
46,1032,1515698,67,11,1,11,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
47,1033,1928050,67,12,2,12,8.0,196,1,1,...,Mid-range product,Regularly busy,Regularly busy,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
48,1034,1949274,67,13,1,10,6.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Average_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer
49,1035,551869,67,14,1,9,7.0,196,1,1,...,Mid-range product,Regularly busy,Busiest_days,Most_orders,23.0,Regular customer,9.360000,Low spender,15.0,Regular customer

In [78]:
ords_prods_merge.to_pickle(os.path.join(file_location, '02 Data', 'prepared data', 'orders_products_merged_v3.pkl'))